services:
  - type: web
    name: forex-calculator
    env: node
    runtime: "node:18.x"
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: EXCHANGE_RATE_API_KEY
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
      - key: PORT
        value: "10000"
    healthCheckPath: /api/uptime
    plan: free
