services:
  - type: web
    name: forex-calculator
    env: node
    buildCommand: npm install && npm run render-build
    startCommand: npm run render-start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: EXCHANGE_RATE_API_KEY
        sync: false
