services:
  - type: web
    name: forex-calculator
    env: node
    runtime: "node:18.x"
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: EXCHANGE_RATE_API_KEY
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
      - key: PORT
        value: "10000"
      - key: NEXT_PUBLIC_BASE_URL
        fromService:
          type: web
          name: forex-calculator
          envVarKey: RENDER_EXTERNAL_URL
    healthCheckPath: /api/health
    plan: free
